# This workflow build and publishes an npm package to NPM registry

name: Publish Package - NPM registry

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-npmjs:
    name: Publish package to npmjs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup .npmrc file to publish to npm
      - name: Setup Web environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
          cache: "yarn" # or 'npm'

      - name: Install packages
        run: yarn install --immutable # or 'npm ci'

      - name: Build the plugin
        run: yarn build # or 'npm run build'

      # Need to add npm access token as secret in the repo, named 'NPM_TOKEN' in this case
      # optional `--provenance` adds provenance statements, to publicly establish where a package was built and who published a package.
      - name: Publish Package
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
